-- TJF 3.0 schema reference
-- Production schema is already applied in Supabase.
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null default '',
  price numeric(10,2) not null default 0 check (price >= 0),
  category text not null check (category in ('masculino','feminino','unissex','luxuria')),
  description text not null default '',
  image_url text not null default '',
  image_path text,
  active boolean not null default true,
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
